// <auto-generated />
using System;
using DistributedChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DistributedChatDbContext))]
    [Migration("20260725232556_AddPrivateRoomsAndManagement")]
    partial class AddPrivateRoomsAndManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedChat.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("RoomId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_messages_room_id_created_at_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.ProcessedEvents.ProcessedEvent", b =>
                {
                    b.Property<string>("ConsumerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumer_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("ConsumerId", "EventId")
                        .HasName("pk_processed_events");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_events_processed_at");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_token_hash");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rooms_created_at");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InviteTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_invite_token_hash");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.Rooms.RoomMember", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("RoomId", "UserId")
                        .HasName("pk_room_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_room_members_user_id");

                    b.ToTable("room_members", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.Users.UserPresence", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instance_id");

                    b.Property<int>("ConnectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("connection_count");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "InstanceId")
                        .HasName("pk_user_presences");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_user_presences_instance_id");

                    b.HasIndex("UserId", "ConnectionCount", "LastHeartbeatAt")
                        .HasDatabaseName("ix_user_presences_user_id_active_heartbeat");

                    b.ToTable("user_presences", (string)null);
                });

            modelBuilder.Entity("DistributedChat.Domain.Messages.Message", b =>
                {
                    b.HasOne("DistributedChat.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_rooms_room_id");

                    b.HasOne("DistributedChat.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_user_id");
                });

            modelBuilder.Entity("DistributedChat.Domain.Rooms.Room", b =>
                {
                    b.HasOne("DistributedChat.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_users_created_by_user_id");
                });

            modelBuilder.Entity("DistributedChat.Domain.Rooms.RoomMember", b =>
                {
                    b.HasOne("DistributedChat.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_members_rooms_room_id");

                    b.HasOne("DistributedChat.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_members_users_user_id");
                });

            modelBuilder.Entity("DistributedChat.Domain.Users.UserPresence", b =>
                {
                    b.HasOne("DistributedChat.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_presences_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
